language: python
sudo: false

cache:
  pip: true

python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

    - python: "3.7"
      name: linting
      dist: xenial
      sudo: true
      install: pip install black flake8
      script:
        - black --check
        - flake8

    - python: "3.8-dev"
      dist: xenial
      sudo: true

install:
  - pip install -r ./dev-requirements.txt
  - pip install -e .

script:
  - py.test tests/
