language: python

cache:
  pip: true

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - python: "3.7"
      name: linting
      install: pip install black flake8
      script:
        - black --check *.py tests/
        - flake8

install:
  - pip install -r ./dev-requirements.txt
  - pip install -e .

script:
  - py.test tests/
