language: python
sudo: false

cache:
  pip: true

python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - pip install pytest
  - pip install -e .

script:
  - py.test tests/
